name: worker
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: worker
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Install Protoc
      run: sudo apt install -y protobuf-compiler
    - name: Install Rust toolchain
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true
        components: rustfmt
    - name: Generate protobuf 
      run: |
        find src/proto -name "*.proto" -exec protoc --experimental_allow_proto3_optional --rust_out=src/proto --proto_path=src/proto {} +
    - name: Build
      run: cargo build -p worker